apiVersion: v1
kind: Secret
metadata:
  name: azure-secret
type: Opaque
data:
  azurestorageaccountname: YXJjaHdheTA0MDQ=
  azurestorageaccountkey: VHCTBg3dJuLiTNpXmVHNH4gvdnGqRs4Z7pYLKw4D76+Y/1X/YHX86A+4AznhM8X0RS+LmW8dVIrrg/f3+3VY1w==